# Generated by Django 4.2.8 on 2024-01-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musician', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musicians',
            name='Instrument_type',
            field=models.CharField(max_length=50),
        ),
    ]
